pipeline {
    agent {
        docker {
            image 'redhat/ubi8'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                //sh './jenkins/scripts/test.sh'
                echo 'testing stage...'
            }
        }
        stage('Deliver') {
            steps {
                echo 'testing stage...'
                //sh './jenkins/scripts/deliver.sh'
                //input message: 'Finished using the web site? (Click "Proceed" to continue)'
                //sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
